baseURL = 'http://trevortomlin.github.io/'
languageCode = 'en-us'
title = "Trevor's Blog"
theme = 'terminal'

[params]
themeColor = "green"
fullWidthTheme = false
centerTheme = true

[languages]
  [languages.en]
    title = "Trevor's Blog"
    subtitle = "Blog For Computer Science Topics"
    keywords = ""
    copyright = "Copyright © 2022 Trevor Tomlin"
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"

    [languages.en.params.logo]
      logoText = "Trevor's Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"